# This is a basic workflow to help you get started with Actions

name: CI/CD Nightly

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop, feature/deployment ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean assemble

      - name: Prepare Cloud Build
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Cloud Run Deployment
        run: |
          touch empty.ignore
          gcloud config set project model-link-272316
          gcloud builds submit --ignore-file=empty.ignore --tag gcr.io/model-link-272316/colivery-api-ng:dev
          gcloud run deploy service-api-ng-nightly \
            --image gcr.io/model-link-272316/colivery-api-ng:dev \
            --concurrency=default \
            --memory=512Mi \
            --set-env-vars=MaxRAM=512m,profiles_active=nightly \
            --region=europe-west1 \
            --platform=managed
        env:
          database_password: ${{ secrets.DEVELOP_DB_PASSWORD }}
