# This is a basic workflow to help you get started with Actions

name: CI/CD Production

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Java Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean assemble

      - name: Prepare Cloud Build
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH_PRD }}

      - name: Cloud Run Deployment
        run: |
          touch empty.ignore
          gsutil cp gs://keystorage-${PROJECT_ID_PRD}/credentials.json credentials.json
          gcloud config set project ${PROJECT_ID_PRD}
          gcloud builds submit --ignore-file empty.ignore --tag gcr.io/${PROJECT_ID_PRD}/machbarschaft-api:stable
          gcloud run deploy machbarschaft-api-sta \
            --image gcr.io/${PROJECT_ID_PRD}/machbarschaft-api:stable \
            --update-env-vars google_maps_api_key=${MAPS_API_KEY_PRD} \
            --region europe-west1 \
            --platform managed
        env:
          MAPS_API_KEY_PRD: ${{ secrets.MAPS_API_KEY_PRD }}
          PROJECT_ID_PRD: ${{ secrets.PROJECT_ID_PRD }}

